# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Jindra Ivánek Blog'
tagline:          'Blogging FSharp'
description:      ''
url:              https://jindraivanek.github.io
baseurl:          /

author:
  name:           'Jindřich Ivánek'
  url:            

paginate:         5

github:
  repo:           https://github.com/jindraivanek/jindraivanek.github.io
